/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedListingsNewRouteImport } from './routes/_authenticated/listings.new'
import { Route as AuthenticatedTradesIndexRouteImport } from './routes/_authenticated/trades.index'
import { Route as AuthenticatedTradesProposalIdRouteImport } from './routes/_authenticated/trades.$proposalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsNewRoute =
  AuthenticatedListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesIndexRoute =
  AuthenticatedTradesIndexRouteImport.update({
    id: '/trades/',
    path: '/trades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesProposalIdRoute =
  AuthenticatedTradesProposalIdRouteImport.update({
    id: '/trades/$proposalId',
    path: '/trades/$proposalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/safety': typeof SafetyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/trades/$proposalId': typeof AuthenticatedTradesProposalIdRoute
  '/trades/': typeof AuthenticatedTradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/safety': typeof SafetyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/trades/$proposalId': typeof AuthenticatedTradesProposalIdRoute
  '/trades': typeof AuthenticatedTradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/safety': typeof SafetyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/listings/new': typeof AuthenticatedListingsNewRoute
  '/_authenticated/trades/$proposalId': typeof AuthenticatedTradesProposalIdRoute
  '/_authenticated/trades/': typeof AuthenticatedTradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/safety'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/listings/new'
    | '/trades/$proposalId'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/marketplace'
    | '/safety'
    | '/admin'
    | '/dashboard'
    | '/matches'
    | '/listings/new'
    | '/trades/$proposalId'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/marketplace'
    | '/safety'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/matches'
    | '/_authenticated/listings/new'
    | '/_authenticated/trades/$proposalId'
    | '/_authenticated/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SafetyRoute: typeof SafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/new': {
      id: '/_authenticated/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof AuthenticatedListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/': {
      id: '/_authenticated/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthenticatedTradesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades/$proposalId': {
      id: '/_authenticated/trades/$proposalId'
      path: '/trades/$proposalId'
      fullPath: '/trades/$proposalId'
      preLoaderRoute: typeof AuthenticatedTradesProposalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedListingsNewRoute: typeof AuthenticatedListingsNewRoute
  AuthenticatedTradesProposalIdRoute: typeof AuthenticatedTradesProposalIdRoute
  AuthenticatedTradesIndexRoute: typeof AuthenticatedTradesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedListingsNewRoute: AuthenticatedListingsNewRoute,
  AuthenticatedTradesProposalIdRoute: AuthenticatedTradesProposalIdRoute,
  AuthenticatedTradesIndexRoute: AuthenticatedTradesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MarketplaceRoute: MarketplaceRoute,
  SafetyRoute: SafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
